### ISSUE TITLE
interstitital make restart my app 

### ISSUE THREAD

**Issue by hvar90** [googlesamples/android-ads#13] opened 2019-05-15 19:29 UTC
library version 
com.google.android.gms:play-services-ads:16.0.0
and also 
com.google.android.gms:play-services-ads:17.2.0

my device is a samsung but this error happens on different devices

the error happen when try to show a loaded interstitial 

the error make restart my app 

```
2019-05-15 13:43:13.397 2981-3597/? E/ActivityManager: Transaction too large, intent: Intent { cmp=schan.main/com.google.android.gms.ads.AdActivity (has extras) }, extras size: 869436, icicle size: 0
2019-05-15 13:43:13.399 2981-3597/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 872224)
2019-05-15 13:43:13.401 2981-3597/? W/ActivityManager: Exception when starting activity schan.main/com.google.android.gms.ads.AdActivity
    android.os.TransactionTooLargeException: data parcel size 872224 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:784)
        at android.app.IApplicationThread$Stub$Proxy.scheduleLaunchActivity(IApplicationThread.java:1278)
        at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1873)
        at com.android.server.am.ActivityStackSupervisor.startSpecificActivityLocked(ActivityStackSupervisor.java:2023)
        at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:3513)
        at com.android.server.am.ActivityStack.resumeTopActivityUncheckedLocked(ActivityStack.java:2869)
        at com.android.server.am.ActivityStack.resumeTopActivityUncheckedLocked(ActivityStack.java:2849)
        at com.android.server.am.ActivityStackSupervisor.resumeFocusedStackTopActivityLocked(ActivityStackSupervisor.java:2620)
        at com.android.server.am.ActivityStack.completePauseLocked(ActivityStack.java:1930)
        at com.android.server.am.ActivityStack.activityPausedLocked(ActivityStack.java:1840)
        at com.android.server.am.ActivityManagerService.activityPaused(ActivityManagerService.java:10083)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:317)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4032)
        at android.os.Binder.execTransact(Binder.java:705)
2019-05-15 13:43:13.405 2981-3597/? W/ActivityManager: Scheduling restart of crashed service schan.main/com.amazonaws.mobileconnectors.s3.transferutility.TransferService in 1000ms

```

**Comment by hvar90** [comment] 2019-05-15 22:19
i found this discussion about my problem 
https://groups.google.com/forum/#!msg/google-admob-ads-sdk/V5w_sWehpKM/3c6FWOgwhNkJ
and this 
https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/android/IL_usiG2g0Q

**Comment by lordamon** [comment] 2019-05-16 08:19
Hi hvar90,
we have the same problem, looks like a bad creativity is running on our ads-slot.
did you catch the specific creativity id with charles proxy? We are trying to catch it but it only sometimes happends to our users.

**Comment by hvar90** [comment] 2019-05-16 20:33
> Hi hvar90,
> we have the same problem, looks like a bad creativity is running on our ads-slot.
> did you catch the specific creativity id with charles proxy? We are trying to catch it but it only sometimes happends to our users.



what is the creativity id? i am using Fiddler to see the traffic but i don't know where is the creativity id

**Comment by stowy** [comment] 2019-07-18 16:27
Hi, thanks for your query.

For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.

**Comment by codingjeremy** [comment] 2019-10-14 22:34
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories

**Closed as completed by codingjeremy** 2019-10-14 22:34 UTC
